### ISSUE TITLE
cargo audit does not work on Rust 1.44 anymore

### ISSUE THREAD

**Issue by galich** [RustSec/cargo-audit#254]
While running `cargo install cargo-audit --force` with Rust 1.44 we are getting following [error in smol_str](https://github.com/rust-analyzer/smol_str/issues/25):

```
error[E0658]: `while` is not allowed in a `const fn`
  --> C:\Users\serg\.cargo\registry\src\github.com-1ecc6299db9ec823\smol_str-0.1.17\src\lib.rs:58:9
   |
58 | /         while i < text.len() {
59 | |             buf[i] = text.as_bytes()[i];
60 | |             i += 1
61 | |         }
   | |_________^
   |
   = note: see issue #52000 <https://github.com/rust-lang/rust/issues/52000> for more information
```

`cargo-audit` uses `crates-index` which uses `smol_str` and now "cargo audit requires Rust 1.40 or later." claim does not hold.

our CI runs cargo audit and must keep running on Rust 1.44 due to performance issues with 1.45-1.46.

would it be possible to pin smol_str in Cargo.lock to something that works with older compiler versions?

**Comment by tarcieri** [comment]
That's unfortunate. The `rustsec` crate explicitly pins to `crates-index` version `=0.15.0` to avoid these sorts of problems, but it seems that was insufficient to prevent `smol_str` from publishing an MSRV-breaking change (this is why I wish all crates did a minor version bump when making MSRV-breaking changes).

About the only option here AFAICT is to add `smol_str` as a direct dependency of the `rustsec` crate, and pin that to a specific release as well.

**Comment by galich** [comment]
in my tests smol_str v0.1.16 works, but smol_str v0.1.17 doesn't

**Comment by tarcieri** [comment]
@galich see if you can `cargo install` from `--git` now. If that works, I'll cut another release.

**Comment by galich** [comment]
@tarcieri I'm, running `cargo install --git https://github.com/RustSec/cargo-audit.git` and still getting this error. It's using commit 0649639d

I wonder what am I doing wrong?

**Comment by tarcieri** [comment]
Oh, I see what's wrong. It looks like you added `smol_str` to `[dev-dependencies`]...

**Comment by galich** [comment]
right, it worked for `cargo build` but doesn't for `cargo install`... fixing

**Comment by galich** [comment]
@tarcieri fix is here https://github.com/RustSec/cargo-audit/pull/258
